import { Theme } from '../types'
import { palette } from './palette'

export const baseTheme: Theme = {
  light: {
    background: palette.white,
    foreground: palette.black,
    primary: palette.neutral[800],
    primaryForeground: palette.white,
    secondary: palette.neutral[300],
    secondaryForeground: palette.neutral[950],
    muted: palette.neutral[100],
    mutedForeground: palette.neutral[500],
    card: palette.white,
    cardForeground: palette.neutral[950],
    accent: palette.cyan[300],
    accentForeground: palette.cyan[900],
    destructive: palette.red[600],
    destructiveForeground: palette.white,
    border: palette.neutral[500],
    success: palette.green[600],
    successForeground: palette.white,
    warning: palette.gold[300],
    warningForeground: palette.black,
    info: palette.blue[300],
    infoForeground: palette.white,
  },
  dark: {
    background: palette.neutral[800],
    foreground: palette.white,
    primary: palette.neutral[50],
    primaryForeground: palette.neutral[900],
    secondary: palette.neutral[600],
    secondaryForeground: palette.neutral[50],
    muted: palette.neutral[700],
    mutedForeground: palette.neutral[400],
    card: palette.neutral[700],
    cardForeground: palette.neutral[50],
    accent: palette.cyan[600],
    accentForeground: palette.cyan[50],
    destructive: palette.red[400],
    destructiveForeground: palette.black,
    border: palette.neutral[300],
    success: palette.green[400],
    successForeground: palette.black,
    warning: palette.gold[300],
    warningForeground: palette.black,
    info: palette.blue[300],
    infoForeground: palette.white,
  },
}
