import { Theme } from '../types'
import { palette } from './palette'

export const baseTheme: Theme = {
  light: {
    background: palette.white,
    foreground: palette.black,
    primary: palette.neutral[800],
    primaryForeground: palette.white,
    secondary: palette.neutral[300],
    secondaryForeground: palette.neutral[950],
    muted: palette.neutral[100],
    mutedForeground: palette.neutral[500],
    card: palette.white,
    cardForeground: palette.neutral[950],
    accent: palette.neutral[100],
    accentForeground: palette.neutral[950],
    destructive: palette.red[600],
    destructiveForeground: palette.white,
    border: palette.neutral[500],
    success: palette.green[600],
    successForeground: palette.white,
    brand: palette.cyan[300],
    brandForeground: palette.cyan[900],
  },
  dark: {
    background: palette.neutral[800],
    foreground: palette.white,
    primary: palette.neutral[50],
    primaryForeground: palette.neutral[900],
    secondary: palette.neutral[600],
    secondaryForeground: palette.neutral[50],
    muted: palette.neutral[800],
    mutedForeground: palette.neutral[400],
    card: palette.neutral[700],
    cardForeground: palette.neutral[50],
    accent: palette.neutral[700],
    accentForeground: palette.neutral[50],
    destructive: palette.red[500],
    destructiveForeground: palette.white,
    border: palette.neutral[300],
    success: palette.green[500],
    successForeground: palette.white,
    brand: palette.cyan[600],
    brandForeground: palette.cyan[50],
  },
}
